### ISSUE TITLE
xdrawrect

### ISSUE THREAD

**Issue by ashleymcdonald** [jaagr/dots#1]
Can you please provide xdrawrect that you use to make the background for your bars; i assume its similar to create_frame but takes xdrawrect's parameters, unfortunatly i dont have the skills..yet.. to make this on my own :P Just coming back to linux after many years on OSX.

Cheers

**Comment by jaagr** [comment]
Hey man,

I just created a repository for it at [https://github.com/jaagr/xdrawrect](https://github.com/jaagr/xdrawrect)

Haven't touched the code for a long time, but I still use it to make highlight and shader lines for my status bars.

**Comment by ashleymcdonald** [comment]
Thanks a bunch :)
