### ISSUE TITLE
Your dots set the github username to jaagr

### ISSUE THREAD

**Issue by rawsh** [jaagr/dots#2]
I had to commit using the http://rawsh@github.com method.
E.G. https://github.com/startclean/Chrome-Extension/commit/4312f1863e6de1dda256b75adfb402dcfa761689

**Comment by jaagr** [comment]
It's insane how that's even possible, but I guess it's `[github.user]` in `~/.gitconfig`

**Comment by rawsh** [comment]
Thanks for the file name, @jaagr
