### ISSUE TITLE
Dependices of "Space" Theme?

### ISSUE THREAD

**Issue by TheBabu** [jaagr/dots#4]
What are the stuff that I have to install in order for the "Space" theme to work... I can't get it to work... And just making sure, all I really have to do is copy paste the polybar theme to get the 2 bars, top and bottom? This is a pretty old repository so I won't be surprised if this config is not supported anymore

**Comment by jaagr** [comment]
I just updated the polybar config for the theme so it should work with the latest version.

What other parts of the theme are you having problems with?

**Comment by TheBabu** [comment]
I think I am having problems with fonts and all that stuff... I am running Arch Linux, do you know where I can install the fonts in that config?

**Comment by jaagr** [comment]
They should all be available in the aur.

**Comment by TheBabu** [comment]
Hm... OK I'll check again...

EDIT:
Ah they are there... I'll install them and try them out...

**Comment by TheBabu** [comment]
Also can I ask what is bspwm? From what I see it is a window manager... But in the config it is a module?

**Comment by jaagr** [comment]
It's a WM, like i3, and the polybar module is used to show its workspaces.

**Comment by TheBabu** [comment]
Ah gotcha!

**Comment by TheBabu** [comment]
Say @jaagr is it possible to have this theme for i3?... Just remove the bspwm workspaces with i3 workspaces should work right?

**Comment by TheBabu** [comment]
Also @jaagr Material Icons do not seem to work (On AUR they are considered outdated).... You can see that the wifi or the volume symbol does not appear here... 
![screenshot_2017-03-17_06-12-00](https://cloud.githubusercontent.com/assets/24832107/24044479/a8880274-0ad8-11e7-84ce-7a18159609f0.png)

**Comment by jaagr** [comment]
Yeah you can just use the i3 module instead. Details about it can be found on the polybar wiki. Regarding material icons you could probably just use the outdated package or just replace it with some other icon font.

**Comment by TheBabu** [comment]
Ah OK... And I was able to get those icons back... The reason those icons was outdated because they had switched the name to ttf-material-design-icons instead of ttf-material-icons!

**Comment by TheBabu** [comment]
@jaagr I can't seem to get the i3 module to work... I copy paste the basic settings, but they do not appear... Do I need to do something because this bar was meant for bspwm?

**Comment by jaagr** [comment]
@Hacksaurus did you add it to the list of modules in the bar section?

**Comment by TheBabu** [comment]
Yes...

**Comment by jaagr** [comment]
Could you pastebin your configuration?

**Comment by TheBabu** [comment]
Here ya go!
http://termbin.com/cs3q

**Comment by jaagr** [comment]
Try this configuration:

~~~ dosini
[module/i3]
type = internal/i3
format = <label-state> <label-mode>
index-sort = true
wrapping-scroll = false

label-focused = %index%
label-focused-padding = 2

label-unfocused = %index%
label-unfocused-padding = ${self.label-focused-padding}

label-urgent = %index%!
label-urgent-background = #bd2c40
label-urgent-padding = ${self.label-focused-padding}

label-visible = %index%
label-visible-padding = ${self.label-focused-padding}

label-mode-padding = ${self.label-focused-padding}
label-mode-foreground = #000
label-mode-background = #ffb52a

**Comment by TheBabu** [comment]
I'll try that! I have a lot of questions so bare with me!

1. What would be a config to add systray?... I tried going though the default config and the wiki and I can't seem to find it. 
2. Why does xbacklight disappear when I connect using my monitor? 
3. Is there can automatic way to have connect to monitor in polybar? So if I am not connected to my monitor the bar still shows up.
4. Powermenu gives me options to Shutdown, Terminate WM, etc. but nothing happens if I click them... I am not sure how to fix this...
5. Is there a MPRIS plugin player for polybar?
6. In this screenshot: https://raw.githubusercontent.com/jaagr/dots/master/.local/etc/themer/themes/space/sample.png: there is multiple "bars" for the CPU, how do you make multiple of them?
7. Whenever I switch Audio Sinks the volume plugin does not adapt accourdingly and I have to do Mod+Shift+R to get it working again... is there a workaround for this?

Sorry for so many questions...

EDIT:
The i3 module that you gave me works! I just added background color for focused items!

**Comment by jaagr** [comment]
> What would be a config to add systray?... I tried going though the default config and the wiki and I can't seem to find it.

Just add `tray-position = right` to the bar section of your config.

> Why does xbacklight disappear when I connect using my monitor?

It's probably because your graphics card driver doesn't have xrandr backlight support. You could try the legacy backlight module, [see the wiki for more details on how to configure it](https://github.com/jaagr/polybar/wiki/Module:-backlight).

> Is there can automatic way to have connect to monitor in polybar? So if I am not connected to my monitor the bar still shows up.

Yes, you can use the `monitor-fallback` parameter. For example, if you want polybar to be shown on the external monitor in case it's connected and on the laptop monitor otherwise you can use the following configuration:

~~~ dosini
[bar/mybar]
monitor = <name-of-external-monitor>
monitor-fallback = <name-of-laptop-monitor>
~~~

> Powermenu gives me options to Shutdown, Terminate WM, etc. but nothing happens if I click them... I am not sure how to fix this...

You probably need to change the commands for the menu items in the powermenu module config to fit your system.

> Is there a MPRIS plugin player for polybar?

Not yet, but a [WIP pull-request has been submitted](https://github.com/jaagr/polybar/pull/456) to add support for it. You could use the `custom/script` module if you have your own script for it.

> In this screenshot: https://raw.githubusercontent.com/jaagr/dots/master/.local/etc/themer/themes/space/sample.png: there is multiple "bars" for the CPU, how do you make multiple of them?

I've used the `ramp` tag, and you can [find more information about it in the wiki](https://github.com/jaagr/polybar/wiki/Module:-cpu). Note that you need to have a font that supports the characters used in the wiki, for example `Unifont`.

> Whenever I switch Audio Sinks the volume plugin does not adapt accourdingly and I have to do Mod+Shift+R to get it working again... is there a workaround for this?

No, not using the built-in module. But you could use your own script for this if you have one (using the `custom/script` module).

**Comment by TheBabu** [comment]
Thank you! I just have 3 more questions!
How do you make the icons bigger in the systray?
Is there way to have launchers in on the bar? So I don't have to go type the command in dmenu?
Why is the bluetooth icon like this?
![Uploading Screenshot_2017-03-23_16-58-24.png…]()

**Comment by jaagr** [comment]
> How do you make the icons bigger in the systray?

You can use the `tray-maxsize` property. However, it requires that the tray clients have support for the defined size.

> Is there way to have launchers in on the bar? So I don't have to go type the command in dmenu?

You could use the menu module or a text module, for example:

~~~ dosini
[module/demo]
type = custom/text
content = Launch browser
click-left = firefox &
~~~

> Why is the bluetooth icon like this?

The image link is broken.

**Comment by TheBabu** [comment]
Thanks! I think that's it! This wasn't really an issue, but more of personal questions... Thank you again! Closing this thread!

**Comment by jaagr** [comment]
No problem!
