### ISSUE TITLE
bootstrap.sh

### ISSUE THREAD

**Issue by rowlandwatkins** [jaagr/dots#5]
Hi,

Stupid question, but there's a reference to bootstrap.sh - but I can't find it anywhere....

Cheers,

Rowland

**Comment by jaagr** [comment]
Where is it used? I guess it's the script found here: https://github.com/jaagr/shellscripts

The root of that repo would need to be part of your `PATH`.

**Comment by rowlandwatkins** [comment]
Ahhhh, sorry, didn't think to look in other repos... Many thanks!
